### ISSUE TITLE
Allow saving monthly average

### ISSUE THREAD

**Issue by glessin** [BoldingBruggeman/getm-rewrite#25]
Saving intervals are defined with datetime.timedelta, which does not allow monthly option. Saving monthly averages is quite routine task (to save space at least). There might be a workaround, or something to suggest together with issue #18?

**Comment by jornbr** [comment]
That one at least has a solution:

you can use `interval_units=pygetm.TimeUnit.MONTHS, interval=1`

Or any other value for interval, as appropriate. A little more info [here](https://pygetm.readthedocs.io/en/latest/api/pygetm.output.html#pygetm.output.File)
