### ISSUE TITLE
Can't compile using -DFABM_<INSTITUTE>_BASE

### ISSUE THREAD

**Issue by hpowley** [BoldingBruggeman/getm-rewrite#26]
When installing pygetm, CMake is not picking up the -DFABM arguments as in the README instructions:

![MicrosoftTeams-image](https://github.com/BoldingBruggeman/getm-rewrite/assets/78801223/5a5c8f9b-6cfc-4e2b-9419-f68004a233b4)

We have successfully installed with these arguments in the commit from 14th October (bd74f18c1cbb10be563380c5693dbc744842a975)

**Comment by jornbr** [comment]
Confirmed - we are in the process of switching to a more modern installation procedure, and in that process the ability to specify cmake flags to FABM was lost. I have enabled this again. it now follows the same approach as [pyfabm](https://fabm.net/python): create a new file `setup.cfg` in `<GETMDIR>/python`, and in there, add:

```
[build_ext]
cmake_opts=-DFABM_ERSEM_BASE=<ERSEMDIR>
```

Note that recent FABM versions already include "ersem" in the default institute list (ignored if `-DFABM_ERSEM_BASE` is not provided), so no need to set or customize `FABM_INSTITUTES`.

You'll need a `git pull` to get the new functionality.

**Comment by jornbr** [comment]
There are some issues remaining in the latest version - I'll report back when those are addressed. Until then, I'd suggest holding off on testing.

**Comment by jornbr** [comment]
The remaining issues have been addressed and all tests are passing. Thus, you could now give the `setup.cfg` functionality described above a try.

**Comment by hpowley** [comment]
Thanks, I can also confirm that I can now successfully compile with a specific version of ERSEM.

**Comment by jornbr** [comment]
Great, thanks for reporting back.
